name: bidders
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3
  flutter_svg: ^0.18.1
  logging: ^0.11.4 #Logger
  shared_preferences: ^0.5.7+3
  package_info: ^0.4.1 #for querying information about the application package.
  flutter_spinkit: ^4.1.2+1 #loaders
  url_launcher: ^5.4.10 # for launching a URL on Android and iOS. Supports web, phone, SMS, and email schemes
  simple_animations: ^2.2.1
  dio: 3.0.9 #Api calls
  rxdart: ^0.24.1

  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  google_sign_in: ^4.5.3
  cloud_firestore: ^0.14.0+2
  cached_network_image: ^2.0.0
  shimmer: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Proxima
      fonts:
        - asset: assets/fonts/proxima-nova-soft-regular.otf
          weight: 400
        - asset: assets/fonts/proxima-nova-soft-medium.otf
          weight: 500
        - asset: assets/fonts/proxima-nova-soft-semibold.otf
          weight: 600
        - asset: assets/fonts/proxima-nova-soft-bold.otf
          weight: 700
